### ISSUE TITLE
Login not working after adding cordova-plugin-deeplinks

### ISSUE THREAD

**Issue by jkufrin** [zyra/cordova-plugin-linkedin#48]
Linkedin login had been working fine. After adding cordova-plugin-deeplinks, when my app returns from Linkedin, the LISDKSessionManager is not calling the OpenURL command. It's like the Deeplinks plugin is blocking the LISDKSessionManager from listening for the app to return from Linkedin.

Android is working fine. I'm also able to use other social media logins still in iOS. It seems to be isolated to just iOS version of Linkedin. 

With the OpenURL command not even being called, I can't try what this user was doing.
https://github.com/zyra/cordova-plugin-linkedin/issues/31

The backtrace of the UI Main Thread looks identical in the before and after. It displays 14 lines twice and then 13 lines twice. Then on the before, Linkedin sends it back to my app, the next line is: lisdksession manager  openURL called!,

That last line doesn't fire anymore. How do I keep the LISDKSessionManager listening?

Thanks in advance.

**Comment by ihadeed** [comment]
See https://stackoverflow.com/questions/18695764/how-to-set-many-url-schemes-in-info-plist

**Comment by ihadeed** [comment]
See https://stackoverflow.com/questions/18695764/how-to-set-many-url-schemes-in-info-plist .. you need to modify your project in XCode to accept 2 CFBundleURLSchemes

One of them is your actual URL Scheme .. and the other needs to be `li<linked in app id>`. See `Configure your application's info.plist` section in here: https://developer.linkedin.com/docs/ios-sdk

Not sure how to configure this plugin's `plugin.xml` to append to that array if it exists.. I'll have to figure that out when I have time. Please let me know if you find a good solution.

**Comment by jkufrin** [comment]
Thanks for the quick reply! I checked and the URLSchemes were already setup properly. The LIAppId is also in there. In reviewing the Linkedin SDK docs, I also added the NSExceptionDomains. Nothing else is jumping out at me as missing. 

Upon returning from Linkedin the lisdksession manager openURL is still not being called. Do you have any other ideas about why adding the cordova-plugin-deeplinks would be blocking just Linkedin from listening for it to return?

**Comment by ksteuer** [comment]
Hi Guys! I have the same problem. I think it started just after the last LinkedIn app update. It looks like it does not call deep link properly.

**Comment by jkufrin** [comment]
I don't think it's the Linkedin app. I just downloaded the latest version of Linkedin. When I load an old version of my app, before I added cordova-plugin-deeplinks, and use the login feature it leaves and returns fine to continue the login process. The new version of my app still fails.

**Comment by ksteuer** [comment]
I agree but my latest version of the app (which uses deep links from the Branch.io) was working with the older version of the LinkedIn app.

**Comment by ihadeed** [comment]
@jkufrin 

I'm not very experienced with iOS native development, so I'm just guessing here. 

Looking at this line that handles URI Scheme links: https://github.com/ionic-team/ionic-plugin-deeplinks/blob/master/src/ios/AppDelegate%2BIonicDeeplink.m#L30
It checks if the link was handled. However, the `handleLink` method always returns `YES`, see https://github.com/ionic-team/ionic-plugin-deeplinks/blob/master/src/ios/IonicDeeplinkPlugin.m#L38

So try to edit the code [here](https://github.com/ionic-team/ionic-plugin-deeplinks/blob/master/src/ios/AppDelegate%2BIonicDeeplink.m#L30) and remove the `if(!handled)` so that it runs the code inside the if-statement all the time. That should fix it.. if it does, let me know and I'll open an issue at the Deeplinks repo.

**Comment by jkufrin** [comment]
Those edits didn't work. It stops IonicDeeplinkPlugin from handling the openUrl, but it still doesn't allow the LISDKSessionManager to keep listening for the app to return. When I uninstall Deeplinks, LInkedin plugin works fine. When I reinstall it, AppDelegate+Linkedin openUrl never gets called. 

I also tried switching around the OpenUrl method to match how Facebook works, but that didn't help. 
```- (void)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
[[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:url]];
    if ([LISDKCallbackHandler shouldHandleUrl:url]) {
        [LISDKCallbackHandler application:application openURL:url sourceApplication:[options valueForKey:@"UIApplicationOpenURLOptionsSourceApplicationKey"] annotation:0x0];
    }
//return YES;
}
```

**Comment by ihadeed** [comment]
Well, probably some debugging points or console logs would help. Need to figure out who's running first (deeplinks or linkedin), and who's blocking the other from catching the event.

**Comment by jkufrin** [comment]
I found a workaround. I don't know Obj-C and I'm stumbling through this. It's not pretty, but it's working for me.

AppDelegate+IonicDeepLink.openUrl is overwriting/blocking AppDelegate+LinkedIn.openUrl somehow.

Update AppDelegate+IonicDeeplink.m to include:
```
#import <linkedin-sdk/LISDKCallbackHandler.h>
```
and insert the following on [line 27](https://github.com/ionic-team/ionic-plugin-deeplinks/blob/master/src/ios/AppDelegate%2BIonicDeeplink.m#L27) 
```
    //LOOK FOR LINKEDIN PROTOCOL IN URL
    NSString *str_url = url.absoluteString;
    NSString *str_linkedin = @"li987654321://";
    NSRange match_linkedin;
    match_linkedin = [str_url rangeOfString: str_linkedin];

    //IF LINKEDIN PROTOCOL IS FOUND, POST NOTIFICATION, FIRE LINKEDIN CALLBACK
    if (match_linkedin.location < 9223372036854775807) {
        [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:url]];
        if ([LISDKCallbackHandler shouldHandleUrl:url]) {
            return [LISDKCallbackHandler application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
        }
    }
```

**Comment by jefvanhoyweghen** [comment]
I created an after_prepare cordova hook to solve this issue automatically using the code of @jkufrin .

First create the hook in scripts/fixLinkedInDeeplink.js using the code of the following Gist: https://gist.github.com/jefvanhoyweghen/5af9c4dcca11ec55242d3b518ec08b6c

Be sure to replace the [APP_NAME] and [APP_ID] tags with your own.

Next add the following line to the config.xml of your cordova project. This will make sure that after 

- cordova prepare
- cordova platform add
- cordova build
- cordova run

it will perform the hook. (https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/)

`<hook src="scripts/fixLinkedInDeeplink.js" type="after_prepare" />`
